version: '2.1'
orbs:
  node: circleci/node@5.0.2
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run: node --version
workflows:
  test:
    jobs:
      - install-node-example
      - node/test:
          run-command: test-once
          test-results-for: jest