version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:18.9.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run: npm run lint --workspaces

  test:
    docker:
      - image: cimg/node:18.9.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run: npm run build --workspace main
      - run: npm run test-once-on-ci --workspace tests

workflows:
  lint_and_test:
    jobs:
      - lint
      - test:
          requires:
            - lint
