version: '2.1'

jobs:
  lint:
    docker:
      - image: cimg/node:16.14.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint -w main

  test:
    docker:
      - image: cimg/node:16.14.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm ci
      - run: npm run test-once

workflows:
  version: 2
  provisioning:
    jobs:
      - lint
      - test:
          requires:
            - lint