version: '2.1'

jobs:
  test:
    docker:
      - image: cimg/node:18.8.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm ci
      - run: npm run test-once

workflows:
  version: 2
  provisioning:
    jobs:
      - test