version: 2.1

jobs:
  apply_migrations:
    docker:
      - image: cimg/node:20.4.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run: npm run apply-migrations

  lint:
    docker:
      - image: cimg/node:20.4.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run: npm run lint

  test:
    docker:
      - image: cimg/node:20.4.0
      - image: cimg/postgres:14.0
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run: npm run compile-on-ci --prefix main
      - run: npm run test-once-on-ci --prefix tests

workflows:
  lint_and_apply_migrations_and_test:
    jobs:
      - lint
      - apply_migrations:
          requires:
            - lint
      - test:
          requires:
            - apply_migrations
