version: '2.1'

references:
  nodejs_workspace: &nodejs_workspace
    working_directory: ~/project
    docker:
      - image: cimg/node:18.8.0

jobs:
  install:
    <<: *nodejs_workspace
    steps:
      - checkout
      - run: npm ci

  test:
    <<: *nodejs_workspace
    steps:
      - checkout
      - run: npm run test-once

workflows:
  version: 2
  provisioning:
    jobs:
      - install
      - test:
          requires:
            - install
