version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
  main:
    jobs:
      - install:
          npm-run: ci
          pkg-manager: npm
          version: '16.10'
      - test:
          npm-run: test-once
          pkg-manager: npm
          version: '16.10'
          requires:
            - install