TRUNCATE TABLE IF EXISTS
  PUBLIC.TAG;

TRUNCATE TABLE IF EXISTS
  PUBLIC.TAG_VALUE;

TRUNCATE TABLE IF EXISTS
  PUBLIC.TAG_KEY;

TRUNCATE TABLE IF EXISTS
  PUBLIC.OPERATION;

TRUNCATE TABLE IF EXISTS
  PUBLIC.TRANSFER;

TRUNCATE TABLE IF EXISTS
  PUBLIC.ACCOUNT;

TRUNCATE TABLE IF EXISTS
  PUBLIC.USER;
