TRUNCATE TABLE PUBLIC.TAG_VALUE CASCADE;

TRUNCATE TABLE PUBLIC.TAG_KEY CASCADE;

TRUNCATE TABLE PUBLIC.OPERATION CASCADE;

TRUNCATE TABLE PUBLIC.CATEGORY CASCADE;

TRUNCATE TABLE PUBLIC.GROUP CASCADE;

TRUNCATE TABLE PUBLIC.TRANSFER CASCADE;

TRUNCATE TABLE PUBLIC.ACCOUNT CASCADE;

-- TRUNCATE TABLE PUBLIC.USER CASCADE;
