TRUNCATE TABLE PUBLIC.TAG CASCADE;

TRUNCATE TABLE PUBLIC.TAG_VALUE CASCADE;

TRUNCATE TABLE PUBLIC.TAG_KEY CASCADE;

TRUNCATE TABLE PUBLIC.OPERATION CASCADE;

TRUNCATE TABLE PUBLIC.TRANSFER CASCADE;

TRUNCATE TABLE PUBLIC.ACCOUNT CASCADE;

TRUNCATE TABLE PUBLIC.USER CASCADE;
