CREATE TABLE IF NOT EXISTS
  PUBLIC.USER (
    EMAIL TEXT NOT NULL,
    USER_ID UUID NOT NULL,
    USERNAME TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    CONSTRAINT USER_PKEY PRIMARY KEY (USER_ID)
  );

CREATE TABLE IF NOT EXISTS
  PUBLIC.ACCOUNT (
    ACCOUNT_ID UUID NOT NULL,
    INITIAL_AMOUNT INTEGER NOT NULL,
    NAME TEXT NOT NULL,
    USER_ID UUID NOT NULL,
    CONSTRAINT ACCOUNT_PKEY PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER (USER_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
  );

CREATE TABLE IF NOT EXISTS
  PUBLIC.GROUP (
    GROUP_ID UUID NOT NULL,
    NAME TEXT NOT NULL,
    USER_ID UUID NOT NULL,
    CONSTRAINT GROUP_PKEY PRIMARY KEY (GROUP_ID),
    CONSTRAINT USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER (USER_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
  );

CREATE TABLE IF NOT EXISTS
  PUBLIC.CATEGORY (
    CATEGORY_ID UUID NOT NULL,
    GROUP_ID UUID NOT NULL,
    NAME TEXT NOT NULL,
    USER_ID UUID NOT NULL,
    CONSTRAINT CATEGORY_PKEY PRIMARY KEY (CATEGORY_ID),
    CONSTRAINT GROUP_ID FOREIGN KEY (GROUP_ID) REFERENCES PUBLIC.GROUP (GROUP_ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER (USER_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
  );

CREATE TABLE IF NOT EXISTS
  PUBLIC.TRANSFER (
    AMOUNT INTEGER NOT NULL,
    AT TIMESTAMPTZ NOT NULL,
    FROM_ACCOUNT_ID UUID NOT NULL,
    TO_ACCOUNT_ID UUID NOT NULL,
    TRANSFER_ID UUID NOT NULL,
    USER_ID UUID NOT NULL,
    CONSTRAINT TRANSFER_PKEY PRIMARY KEY (TRANSFER_ID),
    CONSTRAINT FROM_ACCOUNT_ID FOREIGN KEY (FROM_ACCOUNT_ID) REFERENCES PUBLIC.ACCOUNT (ACCOUNT_ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT TO_ACCOUNT_ID FOREIGN KEY (TO_ACCOUNT_ID) REFERENCES PUBLIC.ACCOUNT (ACCOUNT_ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER (USER_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
  );

CREATE TABLE IF NOT EXISTS
  PUBLIC.OPERATION (
    ACCOUNT_ID UUID NOT NULL,
    AMOUNT INTEGER NOT NULL,
    AMOUNT_PER_UNIT INTEGER NOT NULL,
    AT TIMESTAMPTZ NOT NULL,
    CATEGORY_ID UUID NOT NULL,
    COMMENTS TEXT,
    GROUP_ID UUID NOT NULL,
    OPERATION_ID UUID NOT NULL,
    TYPE
      TEXT NOT NULL,
      UNIT_COUNT INTEGER,
      USER_ID UUID NOT NULL,
      CONSTRAINT OPERATION_PKEY PRIMARY KEY (OPERATION_ID),
      CONSTRAINT ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES PUBLIC.ACCOUNT (ACCOUNT_ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
      CONSTRAINT CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.CATEGORY (CATEGORY_ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
      CONSTRAINT GROUP_ID FOREIGN KEY (GROUP_ID) REFERENCES PUBLIC.GROUP (GROUP_ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
      CONSTRAINT USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER (USER_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
  );
