CREATE TABLE IF NOT EXISTS
  PUBLIC.USER (
    CREATED_AT TIMESTAMPTZ NOT NULL,
    DELETED BOOLEAN NOT NULL DEFAULT 'F',
    EMAIL TEXT NOT NULL UNIQUE,
    UPDATED_AT TIMESTAMPTZ,
    USER_ID UUID NOT NULL,
    USERNAME TEXT NOT NULL UNIQUE,
    PASSWORD TEXT NOT NULL,
    CONSTRAINT USER_PKEY PRIMARY KEY (USER_ID)
  );

CREATE TABLE IF NOT EXISTS
  PUBLIC.ACCOUNT (
    ACCOUNT_ID UUID NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL,
    DELETED BOOLEAN NOT NULL DEFAULT 'F',
    INITIAL_AMOUNT INTEGER NOT NULL,
    NAME TEXT NOT NULL,
    UPDATED_AT TIMESTAMPTZ,
    USER_ID UUID NOT NULL,
    CONSTRAINT ACCOUNT_PKEY PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER (USER_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
  );

CREATE TABLE IF NOT EXISTS
  PUBLIC.TRANSFER (
    AMOUNT INTEGER NOT NULL,
    AT TIMESTAMPTZ NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL,
    DELETED BOOLEAN NOT NULL DEFAULT 'F',
    FROM_ACCOUNT_ID UUID NOT NULL,
    TO_ACCOUNT_ID UUID NOT NULL,
    TRANSFER_ID UUID NOT NULL,
    UPDATED_AT TIMESTAMPTZ,
    USER_ID UUID NOT NULL,
    CONSTRAINT TRANSFER_PKEY PRIMARY KEY (TRANSFER_ID),
    CONSTRAINT FROM_ACCOUNT_ID FOREIGN KEY (FROM_ACCOUNT_ID) REFERENCES PUBLIC.ACCOUNT (ACCOUNT_ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT TO_ACCOUNT_ID FOREIGN KEY (TO_ACCOUNT_ID) REFERENCES PUBLIC.ACCOUNT (ACCOUNT_ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER (USER_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
  );

CREATE TABLE IF NOT EXISTS
  PUBLIC.TAG_KEY (
    CREATED_AT TIMESTAMPTZ NOT NULL,
    DELETED BOOLEAN NOT NULL DEFAULT 'F',
    TAG_KEY_ID UUID NOT NULL,
    NAME TEXT NOT NULL,
    UPDATED_AT TIMESTAMPTZ,
    USER_ID UUID NOT NULL,
    CONSTRAINT TAG_KEY_PKEY PRIMARY KEY (TAG_KEY_ID),
    CONSTRAINT USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER (USER_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
  );

CREATE TABLE IF NOT EXISTS
  PUBLIC.TAG_VALUE (
    CREATED_AT TIMESTAMPTZ NOT NULL,
    DELETED BOOLEAN NOT NULL DEFAULT 'F',
    TAG_VALUE_ID UUID NOT NULL,
    NAME TEXT NOT NULL,
    UPDATED_AT TIMESTAMPTZ,
    USER_ID UUID NOT NULL,
    CONSTRAINT TAG_VALUE_PKEY PRIMARY KEY (TAG_VALUE_ID),
    CONSTRAINT USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER (USER_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
  );

CREATE TABLE IF NOT EXISTS
  PUBLIC.GROUP (
    CREATED_AT TIMESTAMPTZ NOT NULL,
    DELETED BOOLEAN NOT NULL DEFAULT 'F',
    GROUP_ID UUID NOT NULL,
    NAME TEXT NOT NULL,
    UPDATED_AT TIMESTAMPTZ,
    USER_ID UUID NOT NULL,
    CONSTRAINT USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER (USER_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
  );

CREATE TABLE IF NOT EXISTS
  PUBLIC.CATEGORY (
    CATEGORY_ID UUID NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL,
    DELETED BOOLEAN NOT NULL DEFAULT 'F',
    GROUP_ID UUID NOT NULL,
    NAME TEXT NOT NULL,
    UPDATED_AT TIMESTAMPTZ,
    USER_ID UUID NOT NULL,
    CONSTRAINT GROUP_ID FOREIGN KEY (GROUP_ID) REFERENCES PUBLIC.GROUP (GROUP_ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER (USER_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
  );

CREATE TABLE IF NOT EXISTS
  PUBLIC.OPERATION (
    ACCOUNT_ID UUID NOT NULL,
    AMOUNT INTEGER NOT NULL,
    AMOUNT_PER_UNIT INTEGER NOT NULL,
    AT TIMESTAMPTZ NOT NULL,
    COMMENTS TEXT,
    CREATED_AT TIMESTAMPTZ NOT NULL,
    DELETED BOOLEAN NOT NULL DEFAULT 'F',
    OPERATION_ID UUID NOT NULL,
    TAGS JSONB NOT NULL DEFAULT '{}'::JSONB,
    TYPE TEXT NOT NULL,
    UNIT_COUNT INTEGER,
    UPDATED_AT TIMESTAMPTZ,
    USER_ID UUID NOT NULL,
    CONSTRAINT OPERATION_PKEY PRIMARY KEY (OPERATION_ID),
    CONSTRAINT ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES PUBLIC.ACCOUNT (ACCOUNT_ID) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER (USER_ID) ON UPDATE NO ACTION ON DELETE NO ACTION
  );
